CREATE TABLE student (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    email       VARCHAR(180) NOT NULL,
    birth_date  DATE,
    active      BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_student_email UNIQUE (email)
);
