CREATE TABLE department (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,

    CONSTRAINT uk_department_name UNIQUE (name)
);

CREATE TABLE course (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20) NOT NULL,
    name            VARCHAR(150) NOT NULL,
    credits         INTEGER NOT NULL,
    department_id   BIGINT NOT NULL,

    CONSTRAINT uk_course_code UNIQUE (code),
    CONSTRAINT ck_course_credits CHECK (credits BETWEEN 1 AND 6),
    CONSTRAINT fk_course_department
        FOREIGN KEY (department_id)
        REFERENCES department(id)
);
