CREATE TABLE student_profile (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    biography       VARCHAR(1000),
    github_url      VARCHAR(250),
    linkedin_url    VARCHAR(250),

    CONSTRAINT uk_student_profile_student UNIQUE (student_id),
    CONSTRAINT fk_student_profile_student
        FOREIGN KEY (student_id)
        REFERENCES student(id)
        ON DELETE CASCADE
);
