CREATE TABLE enrollment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    course_id       BIGINT NOT NULL,
    enrolled_at     TIMESTAMPTZ NOT NULL,
    status          VARCHAR(20) NOT NULL,
    final_grade     NUMERIC(3,2),

    CONSTRAINT uk_enrollment_student_course UNIQUE (student_id, course_id),
    CONSTRAINT ck_enrollment_status
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_enrollment_final_grade
        CHECK (final_grade IS NULL OR final_grade BETWEEN 0.00 AND 5.00),
    CONSTRAINT ck_cancelled_has_no_grade
        CHECK (status <> 'CANCELLED' OR final_grade IS NULL),
    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES student(id),
    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES course(id)
);
